management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  platform:
    name: order-platform
    configuration-source: spring-cloud-config
