server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.wilnan.notification_service.event
        spring.json.value.default.type: com.wilnan.notification_service.event.OrderCreatedEvent
        spring.json.use.type.headers: false
    listener:
      concurrency: 3

app:
  kafka:
    topics:
      order-created: order-created
