spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_DEFAULT_LABEL:main}
          search-paths: ${CONFIG_GIT_SEARCH_PATHS:config-repository}
          clone-on-start: true
          force-pull: true
