spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/order_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094,localhost:9096}
